### ISSUE TITLE
import.js dosen't check to see if deduplicator is running

### ISSUE THREAD

**Issue by easherma** [pelias/openaddresses#126]
Noted in --help:

```
        --deduplicate: (advanced use) Deduplicate addresses using the
                OpenVenues deduplicator: https://github.com/openvenues/address_deduper.
                It must be running at localhost:5000.
```

This point isn't very clear in the docs, and the import script will keep looping around [address-deduplicator] without throwing an error/checking to see if the service is running. :-(

**Comment by orangejulius** [comment]
Yeah, this is not optimal at all. In https://github.com/pelias/pelias/issues/337 we are discussing an overhaul of the deduper, which currently has some problems. One of the requirements would be to start the deduper automatically.

**Comment by orangejulius** [comment]
The deduplicator has been removed in https://github.com/pelias/openaddresses/pull/362 as part of https://github.com/pelias/pelias/issues/703
