### ISSUE TITLE
0 house numbers

### ISSUE THREAD

**Issue by missinglink** [pelias/openaddresses#17]
I'm not sure if these are useful or simply a relic of the OA schema enforcing a housenumber:

http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/search%3Fsize=4&input=0%20west%204th%20and%20oak%20street

```bash
0 west 4th and oak street

1)	0 West 4th & Oak Street, Anniston, AL
2)	0 West 4th Avenue West, Escondido, CA
3)	0 West 4th Avenue, Holly Grove, AR
4)	0 West 4th Street, El Dorado, AR
```

@riordan thoughts?

**Comment by riordan** [comment]
0-addresses are very real and very much a pain in the ass.
this example taken blatantly from "Fasehoods Programmers Believe About
Addresses"

As much of an edge case as it is, we have no choice but to trust it as
valid until proven otherwise, and even then only for that instance.

Part of me is kinda happy that they're zero indexing though.

**Comment by missinglink** [comment]
right, but I assumed that they are very very uncommon?

I suspect that having 2x `0 West 4th Avenue` in 2x different states indicates a data issue?

**Comment by missinglink** [comment]
needs an investigation, I'm pulling this `in-progress` and self-assigning for a look-see

```
 1)	0 South, Woodstock, New Brunswick
 2)	0 South, New Brunswick
 3)	0 South, New Brunswick
 4)	0 Southers, New Brunswick
 5)	0 South, New Brunswick
 6)	0 South, St. George, New Brunswick
 7)	0 South, Doaktown, New Brunswick
 8)	0 South, Saint John, New Brunswick
 9)	0 South, Big Bear City, CA
10)	0 South, San Bernardino County, CA
11)	0 South, New Brunswick
12)	0 South Road, North Frontenac, Ontario
13)	0 South Drive, Mountain View, CA
14)	0 South Street, Morro Bay, CA
15)	0 South Road, North Frontenac, Ontario
16)	0 South Street, San Bernardino County, CA
17)	0 South Street, Macon, GA
18)	0 South Street, Raleigh, NC
19)	0 South Road, North Frontenac, Ontario
20)	0 South Street, Morristown, NJ
21)	0 South Avenue, Felsenthal, AR
22)	0 South Road, San Bernardino County, CA
23)	0 South Street, Parma, ID
24)	0 South Drive, Big Bear City, CA
25)	0 South Street, Adelanto, CA
26)	0 South Alley, Anniston, AL
27)	0 South Road, San Bernardino County, CA
28)	0 South Street, Ashley, OH
29)	0 South Lane, Crest, CA
30)	0 South Avenue, Wake Forest, NC
31)	0 South Road, Adelanto, CA
32)	0 South Street, German, OH
33)	0 South Avenue, Parma, ID
34)	0 South Street, Windsor, Ontario
35)	0 South Road, North Frontenac, Ontario
36)	0 South Street, Brunswick, GA
37)	0 South B Street, Livingston, MT
38)	0 South Grove Street, Ashley, OH
39)	0 South F Street, Carbon County, MT
40)	0 South K Street, Livingston, MT
```

**Comment by riordan** [comment]
They are. Upon further investigation, lots of these don't exist. Not sure
if the OpenAddresses folks are even aware.

Opening a ticket on their end.

**Comment by riordan** [comment]
There's quite a few null entries in these datasets. In all likleyhood, it's
bad outside of their control and is likely from whatever GIS system
exported it in the first place.

**Comment by missinglink** [comment]
@riordan I can't find the upstream ticket for this, did we file one with them in the end?

**Comment by vesameskanen** [comment]
I recently bumped into the this problem with certain Finnish data. It seems to me that OpenAddresses is pretty heavily 'street address' oriented. Data sources, which include also POI/place name data etc. list them as a fake street + zero index. So, many of the listed 'streets' do not exist at all, they are just placenames.
