### ISSUE TITLE
Allow street-less records in white-listed countries

### ISSUE THREAD

**Issue by trescube** [pelias/openaddresses#218]
Some countries allow addresses without streets.  So far, it just appears to be the Czech Republic.  Here are two examples:

* č.p. 360, 79862 Rozstání
* č.ev. 9, 79857 Rakůvka

These can be parsed as: 
```
{
  housenumber: 'č.p. 360',
  postcode: '79862',
  city: 'Rozstání'
}
```

and:
```
{
  housenumber: 'č.ev. 9',
  postcode: '79857',
  city: 'Rakůvka'
}
```

**Comment by orangejulius** [comment]
Duplicate of https://github.com/pelias/pelias/issues/642
