### ISSUE TITLE
import.js filepath is not taken.

### ISSUE THREAD

**Issue by ltbam** [pelias/openaddresses#23]
When I run import.js in bash (exec folder is 'openaddresses-master', PELIAS_CONF set to my conf file)

The importer searches the file in the execution folder instead of getting the datapath path set in the config

my config:
```
"openaddresses": {
      "datapath": "\\\\prod\\..(morepath)...\\openaddresses-collected\\be\\wa\\",
      "files": ["brussels-fr.csv"]
    }
```

I guess smth wrong happens here as the "filePath" variable should be the absolute path, but it contains only the file name.

```
logger.info( 'Importing %s files.', files.length );
  files.forEach( function forEach( filePath ){
    recordStream.append( function ( next ){
      logger.info( 'Creating read stream for: ' + filePath );
      next( importPipelines.createRecordStream( filePath ) );
    });
  });
```

**Comment by orangejulius** [comment]
Hey @ltbam,
Thanks for reporting this! It looks from your datapath like you're doing this on Windows with data on a network share, right? We've definitely never tested that combination :P

If you were looking for a way to contribute, we'd gladly accept a PR if you come up with a fix that works for you. If not, we've been meaning to do more testing of our code on Windows. Now that we know there's an issue we'll be sure to get to it sooner.

Also, I believe the openaddresses importer can take a datapath on the command line as an argument, as well as through the pelias config. Can you tell us if setting the same path works that way? It would be really helpful when making a fix.

Thanks!

**Comment by ltbam** [comment]
Hi @orangejulius ,
yes i'm trying Pelias on a Windows Machine with Network Shares. I can confirm you that it is ok to access Network Shares with a unc path, as long as it is escaped in the config file. Like this for example:
\\\\path\\to\\data\\repos
This definitely works.

I'll test both Solutions you mentioned and will tell you when/if I come up with a fix. 

Thank you.
