### ISSUE TITLE
Limit needed in download_filtered.js

### ISSUE THREAD

**Issue by kylebarron** [pelias/openaddresses#349]
In order to get data for the entire US, I added all 1600 of the current US openaddress files to `imports.openaddresses.files`, and then did `npm run download`. But I didn't realize that this would start 1600 asynchronous curl jobs (which crashed the server). Is there a way to set a limit at, say, 10 or so asynchronous curl jobs at a time?

**Comment by kylebarron** [comment]
Sorry I don't have too many more details; I didn't save the output. But I do remember getting an `Error: spawn EMFILE` error and it successfully downloaded all of the files before crashing. So I'm wondering if maybe the file handles were opened but not closed properly

**Comment by orangejulius** [comment]
Hey @kylebarron,
Thanks for reporting this, and funny timing. I was just taking a look at our various repos and notice that PR https://github.com/pelias/openaddresses/pull/332, which adds a limit to the number of concurrent downloads, never made to our production branch.

I just merged it, so you should see it if you update your local copy. Let me know how it works!

**Comment by kylebarron** [comment]
Thanks! I'll try it on my personal computer later
