### ISSUE TITLE
Identify source file in ID field

### ISSUE THREAD

**Issue by orangejulius** [pelias/openaddresses#35]
Openaddress IDs as stored in our Elasticsearch index are currently just an autoincrementing integer, which isn't very helpful to OA data users and may not be unique across our different sources. Ids should change to have the source file and row in that source file identified in the ID.

**Comment by riordan** [comment]
:+1:

Another reason to ditch `collected.zip` for individual, unprocessed files (pelias/pelias#247)

**Comment by orangejulius** [comment]
Also, the address deduplicator seems to randomize IDs with some sort of hash, so we'll have to take a look at that too.
