### ISSUE TITLE
Sleep between HTTP requests to avoid ban

### ISSUE THREAD

**Issue by severo** [pelias/openaddresses#433]
There is no countrywide data in OpenAddresses for Brazil, thus the solution I thought about is to download 27 states files. The openaddresses section in `pelias.json` is:

```json
"openaddresses": {
      "datapath": "/data/openaddresses",
      "files": [
        "br/ac/statewide.csv",
        "br/al/statewide.csv",
        "br/am/statewide.csv",
        "br/ap/statewide.csv",
        "br/ba/statewide.csv",
        "br/ce/statewide.csv",
        "br/df/statewide.csv",
        "br/es/statewide.csv",
        "br/go/statewide.csv",
        "br/ma/statewide.csv",
        "br/mg/statewide.csv",
        "br/ms/statewide.csv",
        "br/mt/statewide.csv",
        "br/pa/statewide.csv",
        "br/pb/statewide.csv",
        "br/pe/statewide.csv",
        "br/pi/statewide.csv",
        "br/pr/statewide.csv",
        "br/rj/statewide.csv",
        "br/rn/statewide.csv",
        "br/ro/statewide.csv",
        "br/rr/statewide.csv",
        "br/rs/statewide.csv",
        "br/sc/statewide.csv",
        "br/se/statewide.csv",
        "br/sp/statewide.csv",
        "br/to/statewide.csv"
      ]
    }
```

But, as there is no delay between the HTTP requests, only the first five ones are downloaded, and the following ones are rejected:

```bash
$ pelias download oa
info: [openaddresses-download] Attempting to download selected data files: br/ac/statewide.csv,br/al/statewide.csv,br/am/statewide.csv,br/ap/statewide.csv,br/ba/statewide.csv,br/ce/statewide.csv,br/df/statewide.csv,br/es/statewide.csv,br/go/statewide.csv,br/ma/statewide.csv,br/mg/statewide.csv,br/ms/statewide.csv,br/mt/statewide.csv,br/pa/statewide.csv,br/pb/statewide.csv,br/pe/statewide.csv,br/pi/statewide.csv,br/pr/statewide.csv,br/rj/statewide.csv,br/rn/statewide.csv,br/ro/statewide.csv,br/rr/statewide.csv,br/rs/statewide.csv,br/sc/statewide.csv,br/se/statewide.csv,br/sp/statewide.csv,br/to/statewide.csv
info: [openaddresses-download] Downloading br/ac/statewide.csv
info: [openaddresses-download] Downloading br/al/statewide.csv
info: [openaddresses-download] Downloading br/am/statewide.csv
info: [openaddresses-download] Downloading br/ap/statewide.csv
info: [openaddresses-download] Downloading br/ba/statewide.csv
warn: [openaddresses-download] failed to download https://results.openaddresses.io/latest/run/br/ap/statewide.zip: Error: Command failed: unzip -o -qq -d /data/openaddresses /data/openaddresses/br-ap-statewide1xjsSf4dlWvQJ.zip
[/data/openaddresses/br-ap-statewide1xjsSf4dlWvQJ.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /data/openaddresses/br-ap-statewide1xjsSf4dlWvQJ.zip or
        /data/openaddresses/br-ap-statewide1xjsSf4dlWvQJ.zip.zip, and cannot find /data/openaddresses/br-ap-statewide1xjsSf4dlWvQJ.zip.ZIP, period.
...
```

Maybe solutions could be: 1. to make the process sleep for various seconds between every download from the same source, 2. to ignore the file if it has already been downloaded in `/data/openaddresses/` (ie. an option to force re-download or not).

Thanks a lot for reading, and please tell me if I can help in any way.

**Comment by severo** [comment]
Message is:

>Error 1015: You are being rate limited

![Capture d’écran de 2019-09-02 18-37-11](https://user-images.githubusercontent.com/1676121/64127113-b2403000-cdb0-11e9-8ccb-7692850ebc91.png)

**Comment by missinglink** [comment]
Thanks for the report @severo, the OA team introduced the rate-limiting recently and I've already been in contact with them about it.

They've now upped the limit to 10 requests per minute, but once you go over that limit your IP will get blocked for 1 hour.
I'm going to follow up with them to see if we can get this relaxed but it had to be put in place due to some users downloading huge amounts of data repetitively and costing the project a lot of money.

> Note: those limits will likely change over time, so don't take them as gospel

I think you're correct in saying that we should put a pause in the code where there are more than 10 files in the array. Although I would prefer to avoid that, my ideal scenario is that the limits are removed completely.

We'd be happy to merge a PR to enforce limits in our code, and for now, we can hard-code `10 per minute` and `1 hour backoff`, these limits are not a set 'policy' at OA yet so they are likely to change.

**Comment by severo** [comment]
OK, thanks. Please review and comment #434, I tested it and it works as expected.
