### ISSUE TITLE
Error to generate Brasilia/BR state files

### ISSUE THREAD

**Issue by RodSilvaSantos** [pelias/openaddresses#472]
Many errors are being presented in this data: http://results.openaddresses.io/sources/br/df/statewide
You can't download the data for that. The archives have not been updated since 2017-10-02.

The errors we are getting are:

`2020-06-26 21:10:24,671  WARNING: Error in process_one.process()
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/openaddr/process_one.py", line 134, in process
    cache_result = cache(layer + '-' + data_source['name'], data_source, temp_dir, extras)
  File "/usr/local/lib/python3.5/dist-packages/openaddr/__init__.py", line 97, in cache
    downloaded_files = task.download(source_urls, workdir, data_source.get('conform'))
  File "/usr/local/lib/python3.5/dist-packages/openaddr/cache.py", line 367, in download
    metadata = downloader.get_metadata()
  File "/usr/local/lib/python3.5/dist-packages/esridump/dumper.py", line 112, in get_metadata
    metadata_json = self._handle_esri_errors(response, "Could not retrieve layer metadata")
  File "/usr/local/lib/python3.5/dist-packages/esridump/dumper.py", line 59, in _handle_esri_errors
    response.text,
esridump.errors.EsriDownloadError: Could not retrieve layer metadata: HTTP 503 <html>
<head>`

**Comment by orangejulius** [comment]
Hi @RodSilvaSantos,
Did you mean to open this in the https://github.com/openaddresses/openaddresses repository?

This repository is for the code within the Pelias Geocoder that reads OpenAddresses data. It doesn't do any work to generate that data itself, and it doesn't include any Python code.

I'm assuming this isn't a Pelias issue, so I'm closing this, but feel free to re-open and comment if I got it wrong. The OpenAddresses folks will appreciate your report, they're good people :)

**Comment by RodSilvaSantos** [comment]
Sorry, I reported in the wrong place. 

Thanks for the orientation.
