### ISSUE TITLE
Configure admin lookup and deduplication via pelias.config

### ISSUE THREAD

**Issue by orangejulius** [pelias/openaddresses#51]
Unlike most of our other importers, this importer _only_ allows configuration of admin lookup and deduplication via command line flags. This makes it difficult to point to a single place where configuration changes can be made, whether in our production/dev builds, in the vagrant image, or even on a local dev setup. It also makes our Chef configuration more complicated, as the chef recipes have to know about our openaddresses configuration, rather than just start the importer and let the importer worry about configuration.

Connects pelias/pelias#255

**Comment by dianashk** [comment]
+1000
