### ISSUE TITLE
reverse coding in South Bay always gives Palo Alto as city

### ISSUE THREAD

**Issue by drewda** [pelias/openaddresses#6]
Clicking in these four different South Bay cities returns the correct address number and street, but incorrectly identifies them all as in Palo Alto:

![screen shot 2014-12-22 at 9 45 46 am](https://cloud.githubusercontent.com/assets/212369/5528647/6f41fa20-89bf-11e4-9e59-8e9ee5e4286c.png)

**Comment by sevko** [comment]
After speaking with @missinglink and @randymeech , it sounds like we prefer retrieving admin value via coarse reverse geocoding (currently against [quattroshapes](http://quattroshapes.com), but, in the future, a higher-quality polygons dataset), which would resolve this problem. I've opened a separate [issue](https://github.com/pelias/openaddresses/issues/7) for that feature.
